# Step 1: Use a base image with Nginx installed
FROM nginx:alpine

# Step 2: Copy the Flutter build output into the Nginx container
#COPY build/web /usr/share/nginx/html

# Step 3: Expose the default HTTP port
EXPOSE 4000

# Step 4: Start Nginx in the foreground (default entrypoint is fine)
CMD ["nginx", "-g", "daemon off;"]
