# /etc/nginx/nginx.conf

# Main configuration context
user  nginx;
worker_processes  1;

# Specify the events block (this is typically default)
events {
    worker_connections  1024;
}

# Define the http block where the server block should reside
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Log settings (optional)
    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    # Server block to serve your app
    server {
        listen 4000;          # Nginx will listen on port 4000
        server_name localhost; 

        # Path to your Flutter web app's static files
        root /usr/share/nginx/html;  # The root directory where the Flutter build is mounted
        index index.html;

        # Main location to serve static files
        location / {
            try_files $uri $uri/ =404;  # If file not found, return a 404 error
        }
    }
}
