name: smart-search
services:
  search-server:
    image: search-server
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - network
    environment:
      - ES_HOST=elasticsearch
      - ELASTIC_PASSWORD=test123
      - EMBEDDING_MODEL=nomic-embed-text
      - OLLAMA_HOST=ollama
      - LANGCHAIN_API_KEY=
      - LANGCHAIN_TRACING_V2=false
      - LANGCHAIN_PROJECT=found-chapter
    deploy:
      resources:
        limits:
          memory: 1gb
    depends_on:
      - elasticsearch
      - ollama

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    restart: always
    networks:
      - network
    environment:
      - ELASTIC_PASSWORD=test123
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    expose:
      - 9200
    deploy:
      resources:
        limits:
          memory: 4gb

  ollama:
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    expose:
      - 11434
    environment:
      - gpus=all
    networks:
      - network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  network:

volumes:
  ollama_data:
